#!/bin/sh

# PROVIDE: dsbd_lab
# REQUIRE: networking syslog usr
# KEYWORD: shutdown

. /etc/rc.subr

name="dsbd_lab"
rcvar="dsbd_lab_enable"
start_precmd="dsbd_lab_prestart"

mount_point="/mnt/qemu_smb"
smb_share="//10.0.2.4/qemu"

dsbd_lab_enable() {
    sysrc pot_enable="YES"
    sysrc gh_actions_enable="YES"
}

bootstrap_pkg() {
    pkg64 -N || pkg64 bootstrap -fy
    pkg64 install -fy bash curl git pot potnet
}

configure_pot() {
    if [ ! -d "$HOME/pot" ]; then
        git -C "$HOME" clone https://github.com/digicatapult/pot
    fi
    cd "$HOME/pot"

    mkdir -p /usr/local/etc/pot
    echo "# pot configuration file
POT_CACHE=/opt/pot/cache
POT_EXTIF=vtnet0" > /usr/local/etc/pot/pot.conf

    cp -fR ./bin /usr/local/
    cp -fR ./etc/pot /usr/local/etc/
    cp -fR ./share /usr/local/
}

install_act() {
    if [ ! -d "$HOME/act-pot-cheribsd" ]; then
        git -C "$HOME" clone https://github.com/digicatapult/act-pot-cheribsd
    fi
    cd "$HOME/act-pot-cheribsd"
    ./install.sh FREEBSD_VERSION="23.11" POT_MOUNT_BASE=/opt/pot
}

setup_zfs() {
    if ! zpool list | grep -q "jailroot"; then
        zpool create -f jailroot vtbd1
    fi

    zfs list | grep -q "/opt/pot" || zfs create -o mountpoint=/opt/pot -o compression=on zroot/pot
    zfs list | grep -q "/opt/pot/jails" || zfs create -o mountpoint=/opt/pot/jails -o overlay=on -o compression=on jailroot/jails
    zfs mount -a
}

check_and_mount_smb() {
    if ! mount | grep -q "on ${mount_point} "; then
        mkdir -p ${mount_point}
        mount_smbfs -o ro ${smb_share} ${mount_point} || {
            echo "[error] Failed to mount ${smb_share} on ${mount_point}"
            return 1
        }
    fi
}

set_env_vars() {
    env_file="$HOME/.profile"

    if [ -f "${mount_point}/github_pat.secret" ]; then
        GITHUB_TOKEN=$(cat "${mount_point}/github_pat.secret")
        if ! grep -q "GITHUB_TOKEN" $env_file; then
            echo "export GITHUB_TOKEN='${GITHUB_TOKEN}'" >> $env_file
        fi
    fi

    if [ -f "${mount_point}/github_org.txt" ]; then
        GITHUB_ORG=$(cat "${mount_point}/github_org.txt")
        if ! grep -q "GITHUB_ORG" $env_file; then
            echo "export GITHUB_ORG='${GITHUB_ORG}'" >> $env_file
        fi
    fi
}

fetch_manifests() {
    manifests="$HOME/MANIFESTS"
    mkdir -p $manifests
    releases=$(curl -s "https://download.cheribsd.org/releases/arm64/aarch64c/" | grep -Eo "\w{1,}\.\w{1,}" | sort -u)
    for release in $releases; do
        curl -C - "https://download.cheribsd.org/releases/arm64/aarch64c/$release/ftp/MANIFEST" > "$manifests/arm64-aarch64c-$release-RELEASE"
    done
    echo "[info] Fetched CheriBSD manifests"
}

configure_base_sshd() {
    base_dir="/opt/pot/bases/$(echo $releases | tail -n 1)"
    mkdir -p "$base_dir/root/.ssh/"
    
    sshd_config="AuthorizedKeysFile .ssh/authorized_keys
ChallengeResponseAuthentication no
PasswordAuthentication no
PermitRootLogin without-password
PubkeyAuthentication yes
UsePAM no"
    
    echo "$sshd_config" > "$base_dir/etc/ssh/sshd_config"
    echo 'sshd_enable="YES"' >> "$base_dir/etc/rc.conf"
}

dsbd_lab_prestart() {
    check_and_mount_smb
    set_env_vars

    setup_zfs

    bootstrap_pkg
    fetch_manifests

    configure_pot
    pot init

    install_act
    configure_base_sshd
}

load_rc_config $name
run_rc_command "$@"
