name: lint

on: [push]

jobs:
  lint:
    name: Run ShellCheck
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Install ShellCheck
      run: sudo apt-get install shellcheck

    - name: Find shell scripts with \#!/bin/sh or \#!/bin/bash and run ShellCheck
      run: |
        files=$(find . -type f ! -path '*/\.*' -exec grep -lE '^#!(/usr)?/bin/(ba)?sh' {} +)
        if [ -n "$files" ]; then
          shellcheck -a -S warning $files
        else
          echo "No shell scripts with #!/bin/sh or #!/bin/bash shebang found."
        fi
